language: go
go:
- "1.10.2"
- tip
branches:
  only:
  - develop
  - master
install:
  - go get github.com/abiosoft/ishell
  - go get github.com/stretchr/testify/assert
matrix:
  allow_failures:
  - go: master
script:
  - go build -v ./...
  - go test -v ./...
