language: go
go:
- 1.8.3
- tip
branches:
  only:
  - develop
  - master
install:
  - go get github.com/abiosoft/ishell
matrix:
  allow_failures:
  - go: master
script:
  - go build -v ./...
  - go test -v ./...